name: Curate phantom data

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 AM UTC
  workflow_dispatch:     # Allows manual triggering from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      FW_CLI_API_KEY: ${{ secrets.FW_CLI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tqdm numpy flywheel-sdk
          curl https://storage.googleapis.com/flywheel-dist/fw-cli/stable/install.sh | bash

      - name: Run the script
        run: |
          
          python curate.py -apikey $FW_CLI_API_KEY
